version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng02
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    image: danielsarmiento/djangobacktics:0.3
    container_name: dg02
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn djangobackend.wsgi -b 0.0.0.0:8000"
    expose:
      - "8000"